name: router_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.11
  get_it: ^7.6.7
  go_router: ^13.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#974AFB"
  image: "images/icons/splash_icon.png"
  # android_12:
    # color: "#974AFB"
    # icon_background_color: "#111111"
    # image: "images/icons/splash_icon_android12.png"